---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Disable Selinux
      shell: "setenforce 0"
      become: yes

    - name: Restart Nginx
      service: name=nginx state=started
      become: yes

    - name: Persistant Nginx 
      service: name=nginx enabled=yes
      become: yes

    - name: index file
      stat: path=/tmp/index.html
      register: index_file
    
    - name: Move index_file to location
      command: mv /tmp/index.html /usr/share/nginx/html/index.html
      become: yes
      when: index_file.stat.exists
      notify:
      - Restart Nginx

  handlers:
    - name: Restart Nginx
      service: name=nginx state=restarted
      become: yes
